# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Forexify"
client_id = "a1b6705c57793bad21ca4b4138c42ca1"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [
  "https://your-app-url.com/auth/callback",
  "https://your-app-url.com/auth/shopify/callback",
  "https://your-app-url.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false

[build]
dev_store_url = "t1l4n0d3v.myshopify.com"
