# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Forexify"
client_id = "YOUR_CLIENT_ID_HERE"
application_url = "https://your-app-url.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [
  "https://your-app-url.com/auth/callback",
  "https://your-app-url.com/auth/shopify/callback",
  "https://your-app-url.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[app_proxy]
url = "https://your-app-url.com/api/proxy"
subpath = "forexify"

[pos]
embedded = false

[build]
dev_store_url = "YOUR-DEV-SHOP.myshopify.com"
